// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
// / 

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3QHtrkb4efcW2D5ILfhOnPnQ6hAznhIw',
    appId: '1:1065969017070:web:92c82404068ed35aecd3ff',
    messagingSenderId: '1065969017070',
    projectId: 'yaman-9026a',
    authDomain: 'yaman-9026a.firebaseapp.com',
    storageBucket: 'yaman-9026a.appspot.com',
    measurementId: 'G-5NHL7BHV8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnanRJrcAGDhHwcRQMQaefeO3adL0lWRs',
    appId: '1:1065969017070:android:87817712067af44fecd3ff',
    messagingSenderId: '1065969017070',
    projectId: 'yaman-9026a',
    storageBucket: 'yaman-9026a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJi_xYM-qYhcpSXCSpoT-zXphh-pMg3G8',
    appId: '1:1065969017070:ios:d22e8eb996f4c9d2ecd3ff',
    messagingSenderId: '1065969017070',
    projectId: 'yaman-9026a',
    storageBucket: 'yaman-9026a.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJi_xYM-qYhcpSXCSpoT-zXphh-pMg3G8',
    appId: '1:1065969017070:ios:d22e8eb996f4c9d2ecd3ff',
    messagingSenderId: '1065969017070',
    projectId: 'yaman-9026a',
    storageBucket: 'yaman-9026a.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3QHtrkb4efcW2D5ILfhOnPnQ6hAznhIw',
    appId: '1:1065969017070:web:a35b08a3d21553d3ecd3ff',
    messagingSenderId: '1065969017070',
    projectId: 'yaman-9026a',
    authDomain: 'yaman-9026a.firebaseapp.com',
    storageBucket: 'yaman-9026a.appspot.com',
    measurementId: 'G-EVWDYY3C94',
  );

  
}
